AddDensity( name="g0", dx= 0, dy= 0, dz= 0, group="g")
AddDensity( name="g1", dx= 1, dy= 0, dz= 0, group="g")
AddDensity( name="g2", dx=-1, dy= 0, dz= 0, group="g")
AddDensity( name="g3", dx= 0, dy= 1, dz= 0, group="g")
AddDensity( name="g4", dx= 0, dy=-1, dz= 0, group="g")
AddDensity( name="g5", dx= 0, dy= 0, dz= 1, group="g")
AddDensity( name="g6", dx= 0, dy= 0, dz=-1, group="g")
AddDensity( name="g7", dx= 1, dy= 1, dz= 1, group="g")
AddDensity( name="g8", dx=-1, dy= 1, dz= 1, group="g")
AddDensity( name="g9", dx= 1, dy=-1, dz= 1, group="g")
AddDensity( name="g10",dx=-1, dy=-1, dz= 1, group="g")
AddDensity( name="g11",dx= 1, dy= 1, dz=-1, group="g")
AddDensity( name="g12",dx=-1, dy= 1, dz=-1, group="g")
AddDensity( name="g13",dx= 1, dy=-1, dz=-1, group="g")
AddDensity( name="g14",dx=-1, dy=-1, dz=-1, group="g")
AddDensity( name="g15",dx= 1, dy= 1, dz= 0, group="g")
AddDensity( name="g16",dx=-1, dy= 1, dz= 0, group="g")
AddDensity( name="g17",dx= 1, dy=-1, dz= 0, group="g")
AddDensity( name="g18",dx=-1, dy=-1, dz= 0, group="g")
AddDensity( name="g19",dx= 1, dy= 0, dz= 1, group="g")
AddDensity( name="g20",dx=-1, dy= 0, dz= 1, group="g")
AddDensity( name="g21",dx= 1, dy= 0, dz=-1, group="g")
AddDensity( name="g22",dx=-1, dy= 0, dz=-1, group="g")
AddDensity( name="g23",dx= 0, dy= 1, dz= 1, group="g")
AddDensity( name="g24",dx= 0, dy=-1, dz= 1, group="g")
AddDensity( name="g25",dx= 0, dy= 1, dz=-1, group="g")
AddDensity( name="g26",dx= 0, dy=-1, dz=-1, group="g")

#   Phase Field Evolution d3q15:
AddDensity( name="h0", dx= 0, dy= 0, dz= 0, group="h")
AddDensity( name="h1", dx= 1, dy= 0, dz= 0, group="h")
AddDensity( name="h2", dx=-1, dy= 0, dz= 0, group="h")
AddDensity( name="h3", dx= 0, dy= 1, dz= 0, group="h")
AddDensity( name="h4", dx= 0, dy=-1, dz= 0, group="h")
AddDensity( name="h5", dx= 0, dy= 0, dz= 1, group="h")
AddDensity( name="h6", dx= 0, dy= 0, dz=-1, group="h")
AddDensity( name="h7", dx= 1, dy= 1, dz= 1, group="h")
AddDensity( name="h8", dx=-1, dy= 1, dz= 1, group="h")
AddDensity( name="h9", dx= 1, dy=-1, dz= 1, group="h")
AddDensity( name="h10",dx=-1, dy=-1, dz= 1, group="h")
AddDensity( name="h11",dx= 1, dy= 1, dz=-1, group="h")
AddDensity( name="h12",dx=-1, dy= 1, dz=-1, group="h")
AddDensity( name="h13",dx= 1, dy=-1, dz=-1, group="h")
AddDensity( name="h14",dx=-1, dy=-1, dz=-1, group="h")
if (Options$OutFlow){
    AddDensity( name=paste("gold",0:26,sep=""), dx=0,dy=0,dz=0,group="gold")
    AddDensity( name=paste("hold",0:14,sep=""), dx=0,dy=0,dz=0,group="hold")
}

if (Options$split){
    AddDensity( name="f0", dx= 0, dy= 0, dz= 0, group="f")
    AddDensity( name="f1", dx= 1, dy= 0, dz= 0, group="f")
    AddDensity( name="f2", dx=-1, dy= 0, dz= 0, group="f")
    AddDensity( name="f3", dx= 0, dy= 1, dz= 0, group="f")
    AddDensity( name="f4", dx= 0, dy=-1, dz= 0, group="f")
    AddDensity( name="f5", dx= 0, dy= 0, dz= 1, group="f")
    AddDensity( name="f6", dx= 0, dy= 0, dz=-1, group="f")
    AddDensity( name="f7", dx= 1, dy= 1, dz= 1, group="f")
    AddDensity( name="f8", dx=-1, dy= 1, dz= 1, group="f")
    AddDensity( name="f9", dx= 1, dy=-1, dz= 1, group="f")
    AddDensity( name="f10",dx=-1, dy=-1, dz= 1, group="f")
    AddDensity( name="f11",dx= 1, dy= 1, dz=-1, group="f")
    AddDensity( name="f12",dx=-1, dy= 1, dz=-1, group="f")
    AddDensity( name="f13",dx= 1, dy=-1, dz=-1, group="f")
    AddDensity( name="f14",dx=-1, dy=-1, dz=-1, group="f")
    AddDensity( name="f15",dx= 1, dy= 1, dz= 0, group="f")
    AddDensity( name="f16",dx=-1, dy= 1, dz= 0, group="f")
    AddDensity( name="f17",dx= 1, dy=-1, dz= 0, group="f")
    AddDensity( name="f18",dx=-1, dy=-1, dz= 0, group="f")
    AddDensity( name="f19",dx= 1, dy= 0, dz= 1, group="f")
    AddDensity( name="f20",dx=-1, dy= 0, dz= 1, group="f")
    AddDensity( name="f21",dx= 1, dy= 0, dz=-1, group="f")
    AddDensity( name="f22",dx=-1, dy= 0, dz=-1, group="f")
    AddDensity( name="f23",dx= 0, dy= 1, dz= 1, group="f")
    AddDensity( name="f24",dx= 0, dy=-1, dz= 1, group="f")
    AddDensity( name="f25",dx= 0, dy= 1, dz=-1, group="f")
    AddDensity( name="f26",dx= 0, dy=-1, dz=-1, group="f")  
}
